# Screen parameters
SCREEN_WIDTH = 350
SCREEN_HEIGHT = 240

# Selector parameters
INIT_HORIZONTAL = 0
INIT_VERTICAL = 10
HORIZONTAL_SPACE = 70
VERTICAL_SPACE = 70
CURSOR_WIDTH = 60
CURSOR_HEIGHT = 60
CUSROR_INITIAL_POSITION_X = 0
CUSROR_INITIAL_POSITION_Y = 10
MAX_COLUMNS = 5
MAX_ROWS = 3