# Screen parameters
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 350

# Selector parameters
INIT_HORIZONTAL = 0
INIT_VERTICAL = 60
HORIZONTAL_SPACE = 70
VERTICAL_SPACE = 70
CURSOR_WIDTH = 60
CURSOR_HEIGHT = 60
CURSOR_INITIAL_POSITION_X = 0
CURSOR_INITIAL_POSITION_Y = 60
MAX_COLUMNS = 9
MAX_ROWS = 3
LIMIT_RIGHT = HORIZONTAL_SPACE * (MAX_COLUMNS - 1)
LIMIT_DOWN = VERTICAL_SPACE * (MAX_ROWS - 1)